# Generated by Django 2.1.1 on 2018-09-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='phno',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='formdata',
            old_name='name',
            new_name='usrname',
        ),
    ]
